### PR TITLE
Clarify computational process for spherical harmonics

### PR DESCRIPTION
**Pull request by paulmasson**
Thought you might update this yourself, but here it is if you want it. Cheers!

### CODE REVIEW

**Comment by rreusser** [comment]
👏 🎉Apologies, was focused on some other things this afternoon but I really appreciate it!! It's a goal of mine to focus more on explanation and communication rather than just the mechanics of working with graphics and computation. Need more hours in a day. 😞

**Comment by rreusser** [comment]
Also, I can't believe I only just found your website. It's really, really outstanding! I love the detailed explanations with interactive figures. I have so many questions!

**Comment by paulmasson** [comment]
Thanks! Here's my take on presenting spherical harmonics:

https://paulmasson.github.io/math/docs/functions/sphericalHarmonic.html

**Comment by rreusser** [comment]
You may also enjoy Dr. Stein's work (not on spherical harmonics, but along the lines of some of your posts. 😄) https://duetosymmetry.com/tool/kerr-circular-photon-orbits/

Oh, and also [stdlib-js](https://github.com/stdlib-js/stdlib) which has lots of rigorously implemented [special functions](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special) may be of interest, though it doesn't yet have as many nontrivial functions as you. (It's still heavily in progress. I have a super simple script to create a standalone bundle of just a couple functions, which makes it possible to use a la carte.)

**Comment by paulmasson** [comment]
@rreusser don't know if your into VR yet, but I've been experimenting with WebVR visualizations of special functions:

https://paulmasson.github.io/webvr-worlds/functions/

Basic navigation is available for thumbpads, so you can fly around and through the surfaces.

**Pull request merged**
